# Generated by Django 3.2.4 on 2024-04-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caname', models.CharField(max_length=200, null=True)),
                ('capic', models.ImageField(null=True, upload_to='static/card/')),
                ('cadate', models.DateField()),
                ('cacity', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200, null=True)),
                ('cpic', models.ImageField(null=True, upload_to='static/categorypic/')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Mobile', models.CharField(max_length=10, null=True)),
                ('Message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='evnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(max_length=50, null=True)),
                ('epic', models.ImageField(null=True, upload_to='static/epic/')),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('msg', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='placename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, null=True)),
                ('address', models.TextField()),
                ('ppic', models.ImageField(null=True, upload_to='static/Hotel/')),
                ('pdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('passwd', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spic', models.ImageField(null=True, upload_to='static/slider/')),
                ('sdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vigallerys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(max_length=100, null=True)),
                ('vlink', models.TextField(null=True)),
                ('event_des', models.TextField(null=True)),
                ('vdate', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='scategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=200, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('event_picture', models.ImageField(null=True, upload_to='static/event/')),
                ('speaker_picture', models.ImageField(null=True, upload_to='static/speaker/')),
                ('price', models.IntegerField()),
                ('event_date', models.DateField()),
                ('event_detail', models.TextField(null=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.evnames')),
            ],
        ),
        migrations.CreateModel(
            name='incategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=200, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('event_picture', models.ImageField(null=True, upload_to='static/event/')),
                ('speaker_picture', models.ImageField(null=True, upload_to='static/speaker/')),
                ('price', models.IntegerField()),
                ('event_date', models.DateField()),
                ('event_detail', models.TextField(null=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.evnames')),
            ],
        ),
        migrations.CreateModel(
            name='imgallerys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/gallery/')),
                ('event_des', models.TextField(null=True)),
                ('eventdate', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='fcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=200, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('city_name', models.CharField(max_length=200, null=True)),
                ('event_picture', models.ImageField(null=True, upload_to='static/event/')),
                ('speaker_picture', models.ImageField(null=True, upload_to='static/speaker/')),
                ('price', models.IntegerField()),
                ('event_date', models.DateField()),
                ('event_detail', models.TextField(null=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.evnames')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=200, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('event_picture', models.ImageField(null=True, upload_to='static/event/')),
                ('speaker_picture', models.ImageField(null=True, upload_to='static/speaker/')),
                ('price', models.IntegerField()),
                ('event_date', models.DateField()),
                ('event_detail', models.TextField(null=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.evnames')),
            ],
        ),
        migrations.CreateModel(
            name='edcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=200, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('city_name', models.CharField(max_length=200, null=True)),
                ('event_picture', models.ImageField(null=True, upload_to='static/event/')),
                ('speaker_picture', models.ImageField(null=True, upload_to='static/speaker/')),
                ('price', models.IntegerField()),
                ('event_date', models.DateField()),
                ('event_detail', models.TextField(null=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.evnames')),
            ],
        ),
        migrations.CreateModel(
            name='booknow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('event_picture', models.CharField(max_length=400, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('event_date', models.CharField(max_length=100, null=True)),
                ('event_price', models.CharField(max_length=200, null=True)),
                ('booking_date', models.DateField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.evnames')),
            ],
        ),
    ]
