# Generated by Django 3.2.4 on 2024-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_scategory_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcategory',
            name='event_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fcategory',
            name='event_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incategory',
            name='event_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
