# Generated by Django 3.2.4 on 2024-04-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_speaker_name_scategory_event_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scategory',
            name='speaker_picture',
        ),
    ]
