# Generated by Django 3.2.4 on 2024-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_scategory_speaker_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='no_guests',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
