# Generated by Django 3.2.4 on 2024-04-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_scategory_no_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknow',
            name='no_guests',
        ),
    ]
