# Generated by Django 3.2.4 on 2024-04-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_booknow_no_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='no_guests',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
