# Generated by Django 3.2.4 on 2024-04-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_booknow_no_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edcategory',
            old_name='city_name',
            new_name='event_place',
        ),
        migrations.AddField(
            model_name='edcategory',
            name='no_guests',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
