# Generated by Django 3.2.4 on 2024-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20240412_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcategory',
            name='join',
            field=models.TextField(null=True),
        ),
    ]
