# Generated by Django 3.2.4 on 2024-04-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_edcategory_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edcategory',
            name='speaker_picture',
        ),
    ]
