# Generated by Django 3.2.4 on 2024-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_edcategory_speaker_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
