# Generated by Django 3.2.4 on 2024-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_booknow_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
