# Generated by Django 3.2.4 on 2024-04-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_booknow_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evnames',
            name='epic',
        ),
    ]
