# Generated by Django 3.2.4 on 2024-04-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_evnames_epic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcategory',
            name='speaker_picture',
        ),
    ]
