# Generated by Django 3.2.4 on 2024-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_fcategory_speaker_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scategory',
            old_name='event_picture',
            new_name='event_pic2',
        ),
        migrations.AddField(
            model_name='scategory',
            name='event_pic3',
            field=models.ImageField(null=True, upload_to='static/event/'),
        ),
        migrations.AddField(
            model_name='scategory',
            name='event_picture1',
            field=models.ImageField(null=True, upload_to='static/event/'),
        ),
    ]
