# Generated by Django 3.2.4 on 2024-04-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20240413_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scategory',
            old_name='event_pic2',
            new_name='event_picture',
        ),
        migrations.RemoveField(
            model_name='scategory',
            name='event_pic3',
        ),
        migrations.RemoveField(
            model_name='scategory',
            name='event_picture1',
        ),
    ]
