# Generated by Django 3.2.4 on 2024-04-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_incategory_speaker_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcategory',
            name='no_guests',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incategory',
            name='no_guests',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
