# Generated by Django 3.2.4 on 2024-04-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20240413_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='requstprice',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('event_date', models.DateField()),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
