# Generated by Django 3.2.4 on 2024-04-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_requstprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='requstprice',
            name='no_guests',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
