# Generated by Django 3.2.4 on 2024-04-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20240415_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fcategory',
            new_name='Ccategory',
        ),
    ]
