# Generated by Django 3.2.4 on 2024-04-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_rename_fcategory_ccategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccategory',
            old_name='speaker_name',
            new_name='NGO_name',
        ),
        migrations.RemoveField(
            model_name='ccategory',
            name='no_guests',
        ),
        migrations.RemoveField(
            model_name='ccategory',
            name='price',
        ),
    ]
