# Generated by Django 3.2.4 on 2024-04-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20240415_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(null=True)),
                ('pan_card', models.CharField(max_length=200, null=True)),
                ('DOB', models.DateField()),
                ('donation', models.ImageField(null=True, upload_to='static/donation/')),
                ('screenshots', models.ImageField(null=True, upload_to='static/screenshots/')),
            ],
        ),
    ]
