# Generated by Django 3.2.4 on 2024-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_ngo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='donation',
        ),
        migrations.AddField(
            model_name='ccategory',
            name='donation',
            field=models.ImageField(null=True, upload_to='static/donation/'),
        ),
    ]
