# Generated by Django 3.2.4 on 2024-04-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20240416_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='speaker_name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='speaker_picture',
        ),
    ]
