# Generated by Django 3.2.4 on 2024-04-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20240416_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='College_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
