# Generated by Django 3.2.4 on 2024-04-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20240416_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='College_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
