# Generated by Django 3.2.4 on 2024-04-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_events_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='no_guests',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
