# Generated by Django 3.2.4 on 2024-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_events_no_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccategory',
            name='event_picture',
            field=models.ImageField(null=True, upload_to='static/Charitye_Event/'),
        ),
        migrations.AlterField(
            model_name='edcategory',
            name='event_picture',
            field=models.ImageField(null=True, upload_to='static/Education_Event/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_picture',
            field=models.ImageField(null=True, upload_to='static/Event/'),
        ),
        migrations.AlterField(
            model_name='incategory',
            name='event_picture',
            field=models.ImageField(null=True, upload_to='static/Informal_Event/'),
        ),
        migrations.AlterField(
            model_name='placename',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/place/'),
        ),
        migrations.AlterField(
            model_name='scategory',
            name='event_picture',
            field=models.ImageField(null=True, upload_to='static/Social_Event/'),
        ),
    ]
